/*
Problem

A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

Sample Dataset

AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
Sample Output

20 12 17 21
*/


var sample = "GTACACACGAGGATCAGTGCGTAGGGAGGAAGGCGAGACCAACCTATATCATTCCAACTGATCGTTCCCTACTGGTTCATATGCTCGTACCGGCATTCGACCCGGAAGATAGTCGAATCCTGAGGAGTGCTATTTCAAATGGCACCATTCGACGCTGCGATAGGAGCGGCCATAACCAGCATCGCAGTCAGCAAATCATAGGCCCCGGCCGCGAGAGCGCGACAATGGCGACCTGGAAGGGGATGACCCAGCCCTTCTGGATGGTTAGGTCATTATGTTGCACTTCGGAGTAATTACGAGAATTCACGAGTTTCTGGCCATAGAAGACGTCAGCGAGGCATAACTGTTGTGGGCTCGGAGCAACTCCTATCCAGCAACCGCGTAGACAACCTATCCGTTCTTGAGGTGCACTCCAGAGATAGTAATTTGCTTTAATTGAAGAAGACCTTGTCGCACCCTGACCCTTTTAGGCGAACGCCAATAATGTACGGACGCGGCGTCCACTCTTACCAAAACCTAATTTCAGCAGAACAGTGAAGCTGCCCGGCGGTTATAGGTGAAGTGATGCCCCCAGTAAGGCTATGCGACCAGTTCGATATGAGTCTTAAAGAGTACGAATTTGCAAGGAAGGCAAAGTAAATTGGTGGATGAGGGACGCATCCGCCATCACACATCTTCTAGCGTAGATAGTACCGTCCAATGTTACTACCTAACGCACAATGGGATTCCTGGGATCCTCCCGCCTCACAGTGTATTCCGACACGGTCGCACAATAATCCGAGAAATTGCTACGCACCTGGCCATAACGGTCAGTAAACGCGATGATTCTATTGCATTCCTAACTTATTCACGTAGGTGCGCGCGCCTCTTACGTTTTGCCCTACTAGAGTCTACGGGGCTCGGTAAGGCACTCGAATGATTGACCGATCGGTGTCGCGGGTCGAACGTCATGTCCCACGACC";

var counts = { A: 0, T:0, C:0, G:0 }

for (var i = 0; i != sample.length; ++i) {
	switch (sample[i]) {
		case 'A':
			counts["A"]++;
			break;
		case 'C':
			counts["C"]++;
			break;
		case 'G':
			counts["G"]++;
			break;
		case 'T':
			counts["T"]++;
			break;

		default:
			break;
	}
}

console.log("Total counts ATCG: ", counts["A"], counts["C"], counts["G"], counts["T"]);
