/*
Problem

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.

Sample Dataset

AAAACCCGGT
Sample Output

ACCGGGTTTT
*/


var sample = "AAATTCTTAATACGCTCTGAATTGCATAATCCACCAGCATCCGTAAGGCCCGCGTCGCGGCGTGAAATTTGGTAATACTAACCCATGTCAGATACGTGTCTCCTCAGACTATTAAAGCTTATCTGTTGCTGCACCCGACTAGGCGCAAACTGCCTAGGCTCTCAATTGGCTTCGAATCACCACCTTATAGATAGATAGCAGAATCATCAGGCGCTGATCTTACCTCAATTCGGGTCCTATACTTCATCCTCCTATCAGAGACTGCTGTCAGCTGACATACAGCCCCACCGGTCGCAATCTTTGGTTCCCGAGGGAATTGACATATGTCCAAGGAATGCGTGGTGCTACTTGGATTGCGGGAAAATACACGACCCGCTACGTTAGGTCGGAGGTGGAAAAATTCCCCTCTCTGTGGTACCCCGGCAGCAGCGTTTATGGAACGGGAGCTCGTGCCCATGGCGGCGGGATGACGTTCCTCAGAGTGACGTACCCGCGGCGCACTATAATATGGTTGAGAGACTGCGCCTGGTCGGCCGAGGCCGTATCTACTCACTTTCAGACTTCAACGATTAGGAGATAGCTGGCTATCAGGTATGAACCGGGTAAAGACGGACATCCGCGAAAAGGTAGTCCAAACTCGTGCTCCCGGCCGTACGAGGTCAGCAAGCTATATTGGTAAATCCCAAAGACATGCAATAAGCCATAAATAATTCGGCTCTACATTAGTGTGGAGGCAGCACGCGCGCTTATCGGTGGCCTAGACATGACTGCAGTTCCACGTGGCATGGGGCTCGGCGTGATGTTTTGGGGTTAGCGTAACGATATACCAACCGATTTATTTTGGTGGATGAGCTGTTGTGCCGCAGAAGATATAAGTATCAGGCTGGATGCTCCTTAACG";
var output = "";

for (var i = sample.length; i >= 0; --i) {
  switch (sample[i]) {
    case 'A':
      output += 'T';
      break;

    case 'T':
      output += 'A';
      break;

    case 'G':
      output += 'C';
      break;

    case 'C':
      output += 'G';
      break;

    default:
      break;
  }
}

console.log("Output: ", output);
